spring:
  data:
    mongodb:
      uri: ${MONGODB_URI}
      database: sample_mflix
voyage:
  api-key: ${VOYAGE_API_KEY}
  base-url: https://api.voyageai.com/v1
  model: voyage-3-large
  output-dimension: 2048
  vector-index-name: vector_index
  vector-field: plot_embedding_voyage_3_large
  top-k: 10
  num-candidates: 150
logging:
  level:
    org.springframework.data:
          mongodb: DEBUG


